### ISSUE TITLE
swa uses child count for child/children instead of input text

### ISSUE THREAD

**Issue by Luckey-Elijah** [clragon/swan#1]
The command: `.swa > Column > [ Row > [ Flexible(flex: 1), Flexible(flex: 4) ] ]`
will produce

```dart
Column(
  child: Row( // uses `child`
    children: [
      Flexible(flex: 1),
      Flexible(flex: 4),
    ],
  ),
);
```

and I expect the content of the `Column` to be with `children`, not `child` like this:

```dart
Column(
  children: [ // uses `children`
    Row(
      children: [ 
        Flexible(flex: 1),
        Flexible(flex: 4),
      ]
    ),
  ]
);
```

**Comment by clragon** [comment]
this will be fixed in the new release with the new parser, which explicitly checks what was given in the input.

**Comment by clragon** [comment]
this is now deployed
